name: nectargan
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - libffi=3.4.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.12.11
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025b
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - ./
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - coloredlogs==15.0.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - flatbuffers==25.2.10
      - fonttools==4.58.4
      - humanfriendly==10.0
      - idna==3.10
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - kiwisolver==1.4.8
      - matplotlib==3.10.3
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==2.3.1
      - onnxruntime==1.22.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - packaging==25.0
      - pillow==11.2.1
      - protobuf==6.31.1
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyparsing==3.2.3
      - pyqtgraph==0.13.7
      - pyreadline3==3.5.4
      - pyside6==6.9.1
      - pyside6-addons==6.9.1
      - pyside6-essentials==6.9.1
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.2
      - requests==2.32.4
      - scipy==1.16.0
      - shiboken6==6.9.1
      - simsimd==6.4.9
      - six==1.17.0
      - stringzilla==3.12.5
      - sympy==1.14.0
      - tornado==6.5.1
      - typing-extensions==4.14.0
      - typing-inspection==0.4.1
      - urllib3==2.5.0
      - visdom==0.2.4
      - websocket-client==1.8.0
